#ifndef KASOUZA_FABRICA_FABRICA_UTILS_CONSTANTS_H
#define KASOUZA_FABRICA_FABRICA_UTILS_CONSTANTS_H

#define FABRICA_PLAYER_INTERACTION_MAX_LENGTH 5
#define FABRICA_PLAYER_SPEED 5

#define FABRICA_MOUSE_SENSIBILITY 1

#define FABRICA_BLOCK_BREAKING_COOLDOWN 0.5
#define FABRICA_BLOCK_PLACING_COOLDOWN 0.5

#endif
